# https://github.com/renoki-co/laravel-docker-base
FROM javadmnjd/php-alpine:php8.1-alpine3.16

COPY --from=composer:2.4 /usr/bin/composer /usr/bin/

COPY . /var/www/

WORKDIR /var/www/

RUN set -ex \
    && composer install --optimize-autoloader --no-dev \
    && mkdir -p /var/www/storage/logs/ \
    && chown -R www-data:www-data /var/www \
    && mv /var/www/deploy.sh /docker-entrypoint.d/deploy.sh

ENTRYPOINT ["php", "-a"]
