# since we cache composer and packages in github ci, no need to install them here 

FROM javadmnjd/nginx-unit-alpine-php:unit1.28.0-php8.1

COPY . /var/www/

WORKDIR /var/www/

RUN set -ex \
    && mkdir -p /var/www/storage/logs/ \
    && chown -R www-data:www-data /var/www \
    && rm -rf vendor/*/test/ vendor/*/tests/* \
    && mv /var/www/.unit.config.json /docker-entrypoint.d/.unit.config.json \
    && mv /var/www/deploy.sh /docker-entrypoint.d/deploy.sh

EXPOSE 80
