# since we cache composer and packages in github ci, no need to install them here 

FROM javadmnjd/php-alpine:php8.1-alpine3.16

COPY . /var/www/

WORKDIR /var/www/

RUN set -ex \
    && mkdir -p /var/www/storage/logs/ \
    && chown -R www-data:www-data /var/www \
    && rm -rf vendor/*/test/ vendor/*/tests/* \
    && mv /var/www/deploy.sh /docker-entrypoint.d/deploy.sh

ENTRYPOINT ["php", "-a"]
